### ISSUE TITLE
Bug:  Forge build  failed to parse `unrecognised token, /** `

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#2377]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (44f3a4b 2022-07-18T00:09:10.206569Z)

### What command(s) is the bug in?

forge build

### Operating System

macOS (Intel)

### Describe the bug

Running  forge build with debug output I noticed this:

```console
 failed to parse "~/workspace/contracts/lib/Comptroller.sol" ast: 
"[Diagnostic { loc: File(0, 116, 174), level: Error, ty: 
ParserError, message: "unrecognised token
 '/**\n     * @notice Whether or not this market is listed\n     \n*/', 
expected \"(\", \"[\", \"address\", \"bool\", \"byte\", \"bytes\", \"case\", \"default\", \"error\", \"false\", \"function\", \"leave\", \"mapping\", \"payable\", \"string\", \"switch\", \"this\", \"true\", \"type\", \"}\", Bytes, Int, Uint, address, hexnumber, hexstring, identifier, number, rational, string", notes: [] }]". 

Falling back to regex to extract data
```

It successfully compiles, just making note of this error

**Comment by mattsse** [comment]
I believe this was just fixed here https://github.com/hyperledger-labs/solang/pull/925

**Comment by sambacha** [comment]
> I believe this was just fixed here [hyperledger-labs/solang#925](https://github.com/hyperledger-labs/solang/pull/925)

yup, fixed as of forge 0.2.0 (cce3a44 2022-07-20T00:14:55.494548Z)

**Comment by codemedici** [comment]
I'm still getting a parse error, using latest forge 0.2.0 and solidity 0.8.20 

```
> forge fmt --check && pnpm solhint "{script,src,test}/**/*.sol"

Error: ParserError
     ╭─[ERC1155LazyMintable.sol:101:48]
     │
 101 │             uint256 i = _voucher.commissionBps.length;
     │                                                ┬
     │                                                ╰── unrecognised token '(', expected "!=", "%", "%=", "&", "&&", "&=", ")", "*", "**", "*=", "+", "+=", ",", "-", "-=", "/", "/=", ":", ";", "<", "<<", "<<=", "<=", "=", "==", ">", ">=", ">>", ">>=", "?", "]", "^", "^=", "|", "|=", "||", "}"
```

**Comment by DaniPopes** [comment]
This is not related at all, please open a new issue with the full file and forge version. @codemedici
