### ISSUE TITLE
`setUp()` fails when building from source

### ISSUE THREAD

**Issue by pcaversaccio** [foundry-rs/foundry#3686]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e320eb3 2022-11-10T09:21:49.2140657Z)

### What command(s) is the bug in?

forge test

### Operating System

Windows

### Describe the bug

I was playing around with a Foundry integration into a Hardhat project and I encountered a weird bug. To reproduce the bug simply clone my repo here: https://github.com/pcaversaccio/hardhat-project-template-ts. The `forge-std` library is currently pulled directly and not as submodule - this will change in the future but it doesn't matter for the bug.

If you run `forge test` on this repository using Ubuntu & `foundryup` the test will simply pass (you see all the GH Actions are successful). However, if you use Windows & installing from the source you will get the following error:

```
Running 1 test for contracts/test/Greeter.t.sol:ContractTest
[FAIL. Reason: Invalid data] setUp() (gas: 0)
Test result: FAILED. 0 passed; 1 failed; finished in 1.09ms

Failing tests:
Encountered 1 failing test in contracts/test/Greeter.t.sol:ContractTest
[FAIL. Reason: Invalid data] setUp() (gas: 0)
```

The foundry version I'm currently running from Windows is `forge 0.2.0 (e320eb3 2022-11-10T09:21:49.2140657Z)`. I did some digging and if you would simply import `DSTest` instead of `Test` it would work for Windows. After digging more into the problem I figured out that `StdCheats` from `forge-std` is causing the error - if you remove the inheritance in `Test.sol` on `StdCheats` it will run successfully. Can someone support on this weird bug?

A further bug in the context of the above one is coming from the Hardhat Etherscan plugin somehow. Run `yarn test:forge` and you will get the following error:

```
[FAIL. Reason: Invalid data] setUp() (gas: 0)
2022-11-15T09:15:21.049633Z ERROR etherscan: Failed to deserialize response: data did not match any variant of untagged enum ResponseData res="{\"message\":\"OK\",\"result\":[{\"Address\":\"0xb4c79dab8f259c7aee6e5b2aa729821864227e84\"}],\"status\":\"1\"}"
2022-11-15T09:15:21.050264Z ERROR etherscan: Failed to deserialize response: data did not match any variant of untagged enum ResponseData res="{\"message\":\"OK\",\"result\":[{\"Address\":\"0x7109709ecfa91a80626ff3989d68f67f5b1dd12d\"}],\"status\":\"1\"}"
Test result: FAILED. 0 passed; 1 failed; finished in 1.16ms
```

**Comment by avichalp** [comment]
Observing the same issue on MacOS too. And It also goes away if you replace `Test` with `DSTest`.

**Comment by kristovatlas** [comment]
Running `foundryup` to update to forge 0.2.0 (903a073 2022-11-15T00:06:12.539932Z) resolved this bug for me.

**Comment by pcaversaccio** [comment]
If you build it from source on Windows (can't run `foundryup` on Windows) the above described issue appears. Eg running the tests with Ubuntu WSL works smoothly. Anyone can confirm the same bug if you build it from source on macOS?

**Comment by Euraxluo** [comment]
I also ran into this problem building from source

**Comment by Euraxluo** [comment]
Observing the same issue on Windows11 too. And It also goes away if you replace Test with DSTest.

**Comment by DaniPopes** [comment]
On Windows 10
Can reproduce on an older checkout (OP): e320eb3
While build on latest commit works fine: b65d58d
Looks like it was fixed recently

**Comment by pcaversaccio** [comment]
I can confirm that `forge 0.2.0 (7fc6baf 2022-11-17T09:17:02.3351045Z)` resolves this issue. However, I still have the error:

```
Running 1 test for contracts/test/Greeter.t.sol:ContractTest
[PASS] testCreateGreeter() (gas: 17795)
2022-11-17T09:55:27.186765Z ERROR etherscan: Failed to deserialize response: data did not match any variant of untagged enum ResponseData res="{\"message\":\"OK\",\"result\":[{\"Address\":\"0x7109709ecfa91a80626ff3989d68f67f5b1dd12d\"}],\"status\":\"1\"}"
```

Can we keep this issue open to resolve that serde problem or is there already a similar issue?
