### ISSUE TITLE
Cannot verify contract

### ISSUE THREAD

**Issue by efecarranza** [foundry-rs/foundry#4329]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (903a073 2022-11-14T00:07:04.292547Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

```
forge script script/DeployContract.s.sol:DeployContract --rpc-url https://eth-mainnet.alchemyapi.io/v2/XXX --verify --etherscan-api-key XXX -vvvv
[⠢] Compiling...
No files changed, compilation skipped

We haven't found any matching bytecode for the following contracts: [0x54da5057cda764909f4c79ba9fbb2d4a214eeae5].

This may occur when resuming a verification, but the underlying source code or compiler version has changed.
##
Start verification for (0) contracts
All (0) contracts were verified!
```

**Comment by codemedici** [comment]
Same issue here

**Comment by oddaf** [comment]
+1. This happens only after the first time deploying the contract (first time goes well, it seems it is an etherscan thing?)

**Comment by jamalh110** [comment]
I deleted the out folder and then it worked

**Comment by ZrowGz** [comment]
Having the same issue here. It was really strange. Some of the contracts verify some don't. Two were nearly identical with just a single piece of logic different & was able to get it to verify with one script, but the script for the other wouldn't work. So, changed the line in the verifed and it worked there. But only that way, not through the other script or by copy pasting the verifying code into the other file & switching the logic back. 

Feels like I'm going nuts...

**Comment by giuseppecrj** [comment]
Same as @jamalh110, deleting the out folder fixed this for me.

**Comment by codemedici** [comment]
Anyone else got this response?

`ERROR etherscan: Failed to deserialize response`

**Comment by Evalir** [comment]
Closing—need more info, and there are several duplicates that have been fixed. @codemedici your issue might have to do with #4865

**Comment by seunlanlege** [comment]
Currently facing this issue

**Comment by ratankaliani** [comment]
Still running into this, is this related to the usage of `--via-ir`? I'm on Solidity `0.8.25` and I'm still seeing this.

**Comment by cqlyj** [comment]
Same issue, some contracts get verified while some don't. Used to be solved by add the `--legacy` flag but currently not work
