### ISSUE TITLE
implicit trailing `/` in remappings causes file remappings to not resolve

### ISSUE THREAD

**Issue by BlazeWasHere** [foundry-rs/foundry#7527]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (d1ab09d 2024-03-30T00:17:25.901579435Z)

### Operating System

Linux

### Describe the bug

Using remappings.txt
```
ds-test/=lib/ds-test/src/
src/test.sol=src/testPatched.sol
```

when ran with forge (notice how its `src/test.sol/` instead of `src/test.sol`)
```sh
~> forge remappings 
ds-test/=lib/ds-test/src/
src/test.sol/=src/testPatched.sol/
```

expected behavior is similar to dapptools -- no trailing `/` is added to the remapping.

simple testcase:
<details>

<summary>A.t.sol</summary>

```solidity
// SPDX-License-Identifier: GPL-3.0-or-later
pragma solidity ^0.8.6;

import "ds-test/test.sol";

import {Test} from "src/test.sol";

contract ATest is DSTest {
    function test_basic_sanity() public {
        Test.log();
        assertTrue(true);
    }
}
```

</details>

<details>
<summary>test.sol</summary>

```solidity
// SPDX-License-Identifier: GPL-3.0-or-later
pragma solidity ^0.8.6;

library Test {
    event log_string(string);

    function log() internal {
        emit log_string("test");
    }
}
```
</details>

<details>
<summary>testPatched.sol</summary>

```solidity
// SPDX-License-Identifier: GPL-3.0-or-later
pragma solidity ^0.8.6;

library Test {
    event log_string(string);

    function log() internal {
        emit log_string("patched");
    }
}
```
</details>

now we run forge:
```sh
~> forge test -vv
[⠊] Compiling...
No files changed, compilation skipped

Ran 1 test for src/A.t.sol:ATest
[PASS] test_basic_sanity() (gas: 1821)
Logs:
  test
```

with dapptools:
```sh
~> DAPP_REMAPPINGS=$(cat remappings.txt) dapp test --verbosity 2 
 dapp-build: building with linked libraries
dapp: Predeploying test library src/testPatched.sol:Test at 0x0DdeDfFe2789df61F5f76479464F568334414389
dapp: Predeploying test library src/test.sol:Test at 0x5Fe5dAc04fe3527Cf7bDba8798F5A8b5edDfE4Af
Running 1 tests for src/A.t.sol:ATest
[PASS] test_basic_sanity() (gas: 1994)

Success: test_basic_sanity
  
  "patched"
```

it does seem like this will be a breaking change if implemented due to some people who may be relying on this unexpected behavior, wdyt?

**Comment by BlazeWasHere** [comment]
seems like its caused by this
https://github.com/foundry-rs/foundry/blob/a16714ed40f733013d7a80f4f969564175c3318e/crates/config/src/utils.rs#L177-L179

**Comment by zerosnacks** [comment]
This seems related to https://github.com/foundry-rs/foundry/issues/6706

**Comment by BlazeWasHere** [comment]
@zerosnacks  i believe this issue was fixed in https://github.com/foundry-rs/compilers/pull/49 and all tests passed in foundry CI https://github.com/foundry-rs/foundry/pull/8377 so im guessing we are waiting for foundry main to update to the latest version of  `foundry-compilers`

**Comment by zerosnacks** [comment]
Marking as resolved as `foundry-compilers` has been updated: https://github.com/foundry-rs/compilers/commit/ea346377deaf18dc1f972a06fad76df3d9aed8d9

**Comment by BlazeWasHere** [comment]
@zerosnacks doesnt look like original poc has been fixed with latest nightly (00ff367) + (37ea1e9). should i create a test case for this?

```sh
$ DAPP_REMAPPINGS=$(cat remappings.txt) dapp test --verbosity 2  
 dapp-build: building with linked libraries
[...]

  src/A.t.sol:ATest
   ├╴constructor
   └╴test_basic_sanity()
      ├╴log_string("patched") (src/testPatched.sol:8)
[...]
  
  "patched" # <--- this is good :)


$ forge test -vvv 
[...]
Logs:
  test # <--- this is bad :(
```

**Comment by zerosnacks** [comment]
Hi @BlazeWasHere, that would be appreciated. However I'm still not sure what the intended behavior here would be because Foundry does not support remapping individual files to my knowledge, only directories.

**Comment by BlazeWasHere** [comment]
@zerosnacks Correct that Foundry does not support individual file remappings, ideally it should (`foundry-compilers` does) but i think that's related to #6706
