### ISSUE TITLE
forge doc: links to functions or objects in other files don't work

### ISSUE THREAD

**Issue by lilyanB** [foundry-rs/foundry#9506]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0

### What command(s) is the bug in?

forge doc --build --serve

### Operating System

Linux

### Describe the bug

Hello, I need help with the forge doc please.
When I build the doc, some links to functions/objects in the parent contract (when your contract is inherited from the library) don't work. I have created a repo to view a simple example of code: https://github.com/lilyanB/testFoundry/blob/master/src/libraries/lib.sol#L6

The result when I run `forge doc --build --serve`:
![image](https://github.com/user-attachments/assets/caf04b17-abfb-43e7-b3ce-09aef7f9f0c8)

Thanks

**Comment by grandizzy** [comment]
Het @lilyanB that's not the way natspec inheritance work, please checkhttps://docs.soliditylang.org/en/latest/natspec-format.html#inheritance-notes

Please open a ticket if you see problems with using inheritdoc. Thank you

**Comment by lilyanB** [comment]
> Het @lilyanB that's not the way natspec inheritance work, please check https://docs.soliditylang.org/en/latest/natspec-format.html#inheritance-notes
> 
> Please open a ticket if you see problems with using inheritdoc. Thank you

Thanks for your explanation. I have pushed code with another bug I think. there is no documentation in the function accessible directly to the parent of the current contract:

![image](https://github.com/user-attachments/assets/57d0215b-5066-46dc-ae93-daeff928e6dc)

**Comment by grandizzy** [comment]
that's still not how @inheritdoc works, should be something like

```diff
diff --git a/src/Counter.sol b/src/Counter.sol
index 2c0a207..90e9f27 100644
--- a/src/Counter.sol
+++ b/src/Counter.sol
@@ -10,8 +10,8 @@ contract Counter is ParentCounter, ICounter {
         return 100;
     }
 
-    /// @notice more info in {testParentFunction}
-    function testFunctionWithParent() public pure returns (uint256) {
-        return testParentFunction();
+    /// @inheritdoc ParentCounter
+    function testFunctionWithParent() public pure override returns (uint256) {
+        return super.testFunctionWithParent();
     }
 }
diff --git a/src/ParentCounter.sol b/src/ParentCounter.sol
index 4be1482..d48faeb 100644
--- a/src/ParentCounter.sol
+++ b/src/ParentCounter.sol
@@ -2,7 +2,8 @@
 pragma solidity ^0.8.13;
 
 contract ParentCounter {
-    function testParentFunction() public pure returns (uint256) {
+    /// @notice info for testParentFunction
+    function testFunctionWithParent() public pure virtual returns (uint256) {
         return 100;
     }
 }
``

**Comment by lilyanB** [comment]
> that's still not how @inheritdoc works, should be something like
> 
> ```diff
> diff --git a/src/Counter.sol b/src/Counter.sol
> index 2c0a207..90e9f27 100644
> --- a/src/Counter.sol
> +++ b/src/Counter.sol
> @@ -10,8 +10,8 @@ contract Counter is ParentCounter, ICounter {
>          return 100;
>      }
>  
> -    /// @notice more info in {testParentFunction}
> -    function testFunctionWithParent() public pure returns (uint256) {
> -        return testParentFunction();
> +    /// @inheritdoc ParentCounter
> +    function testFunctionWithParent() public pure override returns (uint256) {
> +        return super.testFunctionWithParent();
>      }
>  }
> diff --git a/src/ParentCounter.sol b/src/ParentCounter.sol
> index 4be1482..d48faeb 100644
> --- a/src/ParentCounter.sol
> +++ b/src/ParentCounter.sol
> @@ -2,7 +2,8 @@
>  pragma solidity ^0.8.13;
>  
>  contract ParentCounter {
> -    function testParentFunction() public pure returns (uint256) {
> +    /// @notice info for ParentCounter.testFunctionWithParent function
> +    function testFunctionWithParent() public pure virtual returns (uint256) {
>          return 100;
>      }
>  }
> ```

Thanks for your example. But I want to create a link to the parent contract. When the user clicks on it, it will move directly to the ParentCounter.testparentfunction doc.
for example:
```
@notice This works: {testFunction}
@dev This does not: {testParentFunction}
```

**Comment by beeb** [comment]
@grandizzy the problem is that link resolution in generated docs does not work as it should.

The source code in https://github.com/foundry-rs/foundry/blob/539760c2d158c91c28cc3d3400963e09f49882ba/crates/doc/src/preprocessor/infer_hyperlinks.rs suggests that links in the format `{Artifact-object}` should resolve to a markdown link to the relevant item, even if they are located on other pages, but this does not work. Likewise, links to functions or structs/errors/enums which are declared in a parent contract (from which the current contract inherits) do not work.

As @lilyanB described, links to functions within the same file are resolved correctly, but links to functions in the parent contract are not resolved.

```solidity
// file A.sol
contract A {
    function foo() external {}
}
```

```solidity
// file B.sol
import { A } from "./A.sol";
contract B is A {
    /**
     * @notice You should call {foo} before calling this function
     */
    function bar() external {}
}
```

The link to `foo` does not work.

**Comment by grandizzy** [comment]
Ah, I see, reopening to check above. Thanks
