### ISSUE TITLE
feat(`forge`): forge install should run `git submodule sync`

### ISSUE THREAD

**Issue by CodeSandwich** [foundry-rs/foundry#9611]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.3.0 (68aff72 2024-12-31T00:22:19.465395448Z)

### What command(s) is the bug in?

forge install

### Operating System

Linux

### Describe the bug

I have a fork (https://github.com/CodeSandwich/era-contracts/) of a repo (https://github.com/matter-labs/era-contracts) that I want to use as a dependency. I had the upstream installed as a dependency, so to keep it clean I uninstalled it (`git rm lib/era-contracts && git commit`, which removed `lib/era-contracts` and the entry from `.gitmodules`) and installed it again with `forge install CodeSandwich/era-contracts`. The installation succeeded, it added the appropriate `[submodule "lib/era-contracts"]` to `.gitmodules` along with the correct `url = https://github.com/CodeSandwich/era-contracts`, but when I go to `lib/era-contracts`, it's the upstream that is installed. When I `cd lib/era-contracts/` and `git remote`, I get just `origin`, but `git remote get-url origin` returns `https://github.com/matter-labs/era-contracts`, which is the upstream. Of course I can't check out my fork's branch in the installed dependency submodule, it's the upstream after all. Also when doing `forge install CodeSandwich/era-contracts@fix_system_contracts` which is my branch, I get `Error: Tag: "fix_system_contracts" not found for repo "https://github.com/CodeSandwich/era-contracts"!`, which is wrong but makes some sense since forge installs the upstream, but it also seems aware that I'm asking for the fork.

**Comment by grandizzy** [comment]
@CodeSandwich when you remove a submodule you also have to `git rm --cached path_to_submodule` (for your case `git rm --cached lib/era-contracts`) pretty sure that's the step you missed when unistalled `lib/era-contracts`

See https://git-scm.com/docs/gitsubmodules/2.27.0#_forms
```
 A submodule can be deleted by running git rm <submodule path> && git commit
```

**Comment by zerosnacks** [comment]
Optimistically marking as resolved by comment above, unrelated to Foundry

**Comment by CodeSandwich** [comment]
There's a typo in the issue description, I'm doing `git rm lib/era-contracts`, NOT `rm lib/era-contracts`, the latter wouldn't modify `.gitmodules`. Adding `--cached` doesn't fix the problem.

What fixed it for me was running `git submodule sync` after `forge install ...`, it made the remote URL match `.gitmodules`. Maybe this should be one of steps done by `forge install`?
